# Generated by Django 5.1.4 on 2025-01-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
    ]
