# Generated by Django 5.1.4 on 2025-01-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_list_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='shuffled_text',
            field=models.TextField(default='popa'),
        ),
    ]
