# Generated by Django 5.2.4 on 2025-07-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_list_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='shuffled_text',
        ),
        migrations.AddField(
            model_name='list',
            name='people_array',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='list',
            name='templates',
            field=models.JSONField(default=list),
        ),
    ]
